from models.job import Job
from models.candidate import CandidateProfile


def test_job_id_autogenerated_from_source_and_external_id():
    job = Job(source="telegram", external_id="123:456")
    assert job.id == "telegram:123:456"


def test_job_id_respected_if_explicitly_set():
    job = Job(source="indeed", external_id="abc", id="custom")
    assert job.id == "custom"


def test_job_text_joins_nonempty_fields_only():
    job = Job(source="indeed", external_id="1", title="Vue dev", company="Acme", description="Build stuff")
    assert job.text == "Vue dev\nAcme\nBuild stuff"


def test_job_text_skips_empty_title_and_company():
    job = Job(source="telegram", external_id="1:2", description="Full vacancy text")
    assert job.text == "Full vacancy text"


def test_candidate_profile_from_config_defaults():
    profile = CandidateProfile.from_config(None)
    assert profile.name == ""
    assert profile.skills == []
    assert profile.salary_expectation == ""


def test_candidate_profile_from_config_fills_fields():
    profile = CandidateProfile.from_config({
        "name": "Jane",
        "skills": ["vue", "php"],
        "salary_expectation": "$1500",
    })
    assert profile.name == "Jane"
    assert profile.skills == ["vue", "php"]
    assert profile.salary_expectation == "$1500"


def test_known_facts_text_marks_missing_fields():
    profile = CandidateProfile(name="Jane")
    facts = profile.known_facts_text()
    assert "Jane" in facts
    assert "НЕИЗВЕСТНО" in facts  # salary_expectation, work_authorization и т.д. не заполнены
